### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by RobertWHurst** [giodamelio/edo#1]
This isn't an issue, but rather a thank you.

I love this little library. I think a simple templating library is exactly what the Rust community was lacking. Edo fills that void very nicely. thanks for sharing it with the community 🍻 
I'll do my best to share it around.

**Comment by giodamelio** [comment]
Thanks, that means a lot. I would just like to point out however that this a super half baked project created to fill a need in another project that has since been put on hold (I've been really busy). It's probably broken in any manner of ways and I really don't have much time to maintain it right now.

That being said, if this helps you or anyone else, I'd be happy to accept any contributions.
